# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tradevault
spring.datasource.username=tradevault_user
spring.datasource.password=tradevault123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=tradevault-super-secret-key-must-be-long-enough-for-hs256-algorithm
jwt.expiration=86400000

# Alpha Vantage
alphavantage.api.key=KT97UYFDTSZO40UQ

# Logging
logging.level.com.tradevault=DEBUG